"""Create GitHub issues for archaeologist findings, with dedup."""
from __future__ import annotations

import subprocess
from typing import List

from tools.archaeologist.models import Finding

_LABEL = "tech-debt"
_PREFIX = "[Archaeologist]"


def _existing_archaeologist_issues(repo_name: str) -> List[str]:
    """Return titles of open issues that already have the Archaeologist prefix."""
    try:
        result = subprocess.run(
            ["gh", "issue", "list", "--state", "open", "--search", _PREFIX, "--json", "title", "--jq", ".[].title"],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            return [t.strip() for t in result.stdout.strip().splitlines() if t.strip()]
    except subprocess.TimeoutExpired:
        pass
    return []


def _build_title(repo_name: str, finding: Finding) -> str:
    return f"{_PREFIX} {repo_name}: {finding.finding_type} - {finding.summary}"


def create_issues(
    findings: List[Finding],
    repo_name: str,
    max_issues: int = 5,
) -> List[str]:
    """Create GitHub issues for findings. Returns list of created issue URLs.

    - Deduplicates against existing [Archaeologist] issues
    - Caps at *max_issues* new issues per run
    """
    existing_titles = _existing_archaeologist_issues(repo_name)
    created: List[str] = []

    for finding in findings:
        if len(created) >= max_issues:
            break

        title = _build_title(repo_name, finding)

        # Dedup check
        if any(title in existing for existing in existing_titles):
            continue

        body_lines = [
            f"## {finding.finding_type.replace('_', ' ').title()}",
            "",
            finding.details,
            "",
            "### Affected files",
            "",
        ]
        for f in finding.files[:20]:
            body_lines.append(f"- `{f}`")
        body_lines.append("")
        body_lines.append("---")
        body_lines.append("*Auto-generated by Code Archaeologist*")
        body = "\n".join(body_lines)

        try:
            # Ensure label exists (ignore error if it already does)
            subprocess.run(
                ["gh", "label", "create", _LABEL, "--color", "FBCA04",
                 "--description", "Technical debt identified by automated scanning"],
                capture_output=True, text=True, timeout=15,
            )

            result = subprocess.run(
                ["gh", "issue", "create", "--title", title, "--body", body, "--label", _LABEL],
                capture_output=True, text=True, timeout=30,
            )
            if result.returncode == 0:
                url = result.stdout.strip()
                created.append(url)
        except subprocess.TimeoutExpired:
            continue

    return created
